spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/docutrust}
    username: ${DATABASE_USERNAME:docutrust}
    password: ${DATABASE_PASSWORD:docutrust}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
